//DISHES
export const FETCH_TOP_DISHES = 'FETCH_TOP_DISHES  ';
export const TOP_DISHES_LOADING_FAILED = 'TOP_DISHES_LOADING_FAILED';
export const DISHES_LOADING = 'DISHES_LOADING';

//CHEFS
export const FETCH_TOP_CHEFS = 'FETCH_TOP_CHEFS  ';
export const TOP_CHEFS_LOADING_FAILED = 'TOP_CHEFS_LOADING_FAILED';
export const CHEFS_LOADING = 'CHEFS_LOADING';

//CUISINES
export const FETCH_CUISINES = 'FETCH_CUISINES';
export const CUISINES_LOADING_FAILED = 'CUISINES_LOADING_FAILED';
export const CUISINES_LOADING = 'CUISINES_LOADING';

//*********************ACCOUNTS****************************//
//LOGIN
export const POST_LOGIN_RESPONSE = 'POST_LOGIN_RESPONSE';
export const POST_LOGIN_RESPONSE_FAILED = 'POST_LOGIN_RESPONSE_FAILED';
export const ADD_VALIDATION = 'ADD_VALIDATION';
export const REMOVE_VALIDATION = 'REMOVE_VALIDATION';

//SIGNUP
export const SIGNUP_SUCCESSFULL = 'SIGNUP_SUCCESSFULL';
export const SIGNUP_UNSUCCESSFULL = 'SIGNUP_UNSUCCESSFULL';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

//LOADING
export const ACCOUNT_LOADING = 'ACCOUNT_LOADING';
