//DISHES
export const FETCH_TOP_DISHES = 'FETCH_TOP_DISHES  ';
export const TOP_DISHES_LOADING_FAILED = 'TOP_DISHES_LOADING_FAILED';
export const DISHES_LOADING = 'DISHES_LOADING';

//CHEFS
export const FETCH_TOP_CHEFS = 'FETCH_TOP_CHEFS  ';
export const TOP_CHEFS_LOADING_FAILED = 'TOP_CHEFS_LOADING_FAILED';
export const CHEFS_LOADING = 'CHEFS_LOADING';

//CUISINES
export const FETCH_CUISINES = 'FETCH_CUISINES';
export const CUISINES_LOADING_FAILED = 'CUISINES_LOADING_FAILED';
export const CUISINES_LOADING = 'CUISINES_LOADING';
