//DISHES
export const FETCH_TOP_DISHES = 'FETCH_TOP_DISHES  ';
export const TOP_DISHES_LOADING_FAILED = 'TOP_DISHES_LOADING_FAILED';
export const DISHES_LOADING = 'DISHES_LOADING';

//CHEFS
export const FETCH_TOP_CHEFS = 'FETCH_TOP_CHEFS  ';
export const TOP_CHEFS_LOADING_FAILED = 'TOP_CHEFS_LOADING_FAILED';
export const CHEFS_LOADING = 'CHEFS_LOADING';

//CUISINES
export const FETCH_CUISINES = 'FETCH_CUISINES';
export const CUISINES_LOADING_FAILED = 'CUISINES_LOADING_FAILED';
export const CUISINES_LOADING = 'CUISINES_LOADING';

//*********************ACCOUNTS****************************//
//LOGIN
export const POST_LOGIN_RESPONSE = 'POST_LOGIN_RESPONSE';
export const POST_LOGIN_RESPONSE_FAILED = 'POST_LOGIN_RESPONSE_FAILED';
export const ADD_VALIDATION = 'ADD_VALIDATION';
export const REMOVE_VALIDATION = 'REMOVE_VALIDATION';
export const USER_DATA_JWT = 'USER_DATA_JWT';
export const POST_EXISTING_USER_DATA = 'POST_EXISTING_USER_DATA';

//SIGNUP
export const SIGNUP_SUCCESSFULL = 'SIGNUP_SUCCESSFULL';
export const SIGNUP_UNSUCCESSFULL = 'SIGNUP_UNSUCCESSFULL';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

//LOADING
export const ACCOUNT_LOADING = 'ACCOUNT_LOADING';

//*********************FETCH ALL DISHES****************************//
export const FETCH_ALL_DISHES = 'FETCH_ALL_DISHES';
export const FETCH_ALL_DISHES_FAILED = 'FETCH_ALL_DISHES_FAILED';
export const FETCH_ALL_DISHES_LOADING = 'FETCH_ALL_DISHES_LOADING;';

////*********************ADD TO CARTS****************************//
export const ADD_DETAILS_TO_CART = 'ADD_DETAILS_TO_CART';
export const ADD_DETAILS_TO_CART_FAILED = 'ADD_DETAILS_TO_CART_FAILED';
export const DISABLE_CART_ALERT = 'DISABLE_CART_ALERT';
export const ENABLE_CART_ALERT = 'ENABLE_CART_ALERT';
export const ADD_PRICE_TO_CART = 'ADD_PRICE_TO_CART';
export const REMOVE_PRICE_FROM_CART = 'REMOVE_PRICE_FROM_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CONTENT_ADDED = 'CONTENT_ADDED';
export const ORDER_CONTENT = 'ORDER_CONTENT';

////*********************CHEF****************************//
export const BECOME_A_CHEF = 'BECOME_A_CHEF';
export const IS_CHEF = 'IS_CHEF';
export const IS_BECOMING_A_CHEF_LOADING = 'IS_BECOMING_A_CHEF_LOADING';
