# Generated by Django 3.0.4 on 2020-03-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodnextdoor', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodnextdoor.Dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodnextdoor.Orders')),
            ],
        ),
    ]
